/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'bhim' : IDL.Null,
  'googlePay' : IDL.Null,
  'paytm' : IDL.Null,
  'phonePe' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'utr' : IDL.Opt(IDL.Text),
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'qrCodeData' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepositRequest' : IDL.Func([IDL.Nat, PaymentMethod], [IDL.Text], []),
  'getAllDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getCallerDepositRequests' : IDL.Func(
      [],
      [IDL.Vec(DepositRequest)],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositRequest' : IDL.Func([IDL.Text], [DepositRequest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitUtr' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyPayment' : IDL.Func([IDL.Text, PaymentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'bhim' : IDL.Null,
    'googlePay' : IDL.Null,
    'paytm' : IDL.Null,
    'phonePe' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'utr' : IDL.Opt(IDL.Text),
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'qrCodeData' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepositRequest' : IDL.Func([IDL.Nat, PaymentMethod], [IDL.Text], []),
    'getAllDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerDepositRequests' : IDL.Func(
        [],
        [IDL.Vec(DepositRequest)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositRequest' : IDL.Func([IDL.Text], [DepositRequest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitUtr' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyPayment' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };