/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'utr' : [] | [string],
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'qrCodeData' : string,
  'user' : Principal,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type PaymentMethod = { 'bhim' : null } |
  { 'googlePay' : null } |
  { 'paytm' : null } |
  { 'phonePe' : null };
export type PaymentStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepositRequest' : ActorMethod<[bigint, PaymentMethod], string>,
  'getAllDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getCallerDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositRequest' : ActorMethod<[string], DepositRequest>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitUtr' : ActorMethod<[string, string], undefined>,
  'verifyPayment' : ActorMethod<[string, PaymentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];